version: '3.8'
services:
  
  api:
    container_name: HMS
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    expose:
      - "8080"
    ports:
      - "8181:8181"
      - "4848:4848"
      - "8080:8080"
    labels:
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=Host(`hms.northeurope.cloudapp.azure.com`)"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=buypass"


  reverse-proxy:
    container_name: hms-proxy
    image: traefik:v2.3
    # Enables the web UI and tells Traefik to listen to docker
    ports:
      # Front ports
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/hms-acme.json:/acme.json
      - ${PWD}/hms-proxy.toml:/traefik.toml
